apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: targeting-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/part-of: feature-flags
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: feature-flags

  source:
    repoURL: https://github.com/Arthur-Rosa/FIAP-TCs-Challenge-DevOps
    targetRevision: main
    path: gitops/apps/targeting-service

  destination:
    server: https://kubernetes.default.svc
    namespace: feature-flags

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
