apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: feature-flags
type: Opaque
stringData:
  REDIS_URL: "rediss://feature-flags-redis-cluster-bpkb05.serverless.use1.cache.amazonaws.com:6379/0"
  SERVICE_API_KEY: "tm_key_f1e8a78e1455acafddaa2ad9f1ef71112f3d190a489a4fcb2409d987dfb09f66"
  PORT: "8004"
  # Credenciais AWS para SQS (usar IAM Role recomendado em produção)
  AWS_ACCESS_KEY_ID: "AKIA4MTWHB5UUCFXYHSR"
  AWS_SECRET_ACCESS_KEY: "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"
