apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgres://auth_user:Jg2viSox2ao6UQ0C@feature-flags-auth-db.cluster-c01kesg62uh4.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "feature-flags-master-key-2026"
  PORT: "8001"
