apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: feature-flags
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.feature-flags.svc.cluster.local:8001"
  LOG_LEVEL: "info"
