apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgresql://flags_user:ir7H2OWlcscnRCCD@feature-flags-flag-db.cluster-c01kesg62uh4.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
  PORT: "8002"
