apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: feature-flags
type: Opaque
stringData:
  DATABASE_URL: "postgresql://targeting_user:9xQBen3LocImRuXq@feature-flags-targeting-db.cluster-c01kesg62uh4.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"
  PORT: "8003"
