apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: feature-flags
type: Opaque
stringData:
  # Credenciais AWS para DynamoDB e SQS (usar IAM Role recomendado em produção)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PORT: "8005"
