apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-server-service.yaml
  - project.yaml
  - applications/auth-service-app.yaml
  - applications/flag-service-app.yaml
  - applications/targeting-service-app.yaml
  - applications/evaluation-service-app.yaml
  - applications/analytics-service-app.yaml
